name: Deploy

on:
  push:
    branches: [main]
  schedule:
    # Runs daily at 03:00 Taiwan time (UTC+8).
    - cron: '0 19 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Restart server
        run: |
          curl "$PANEL_URL" \
            --fail-with-body \
            --request POST \
            --header 'Content-Type: application/json' \
            --header 'Accept: */*' \
            --header "Authorization: Bearer $PANEL_KEY" \
            --data '{
              "action": "restart"
            }'
        env:
          PANEL_URL: ${{ secrets.PANEL_URL }}
          PANEL_KEY: ${{ secrets.PANEL_KEY }}
